### ISSUE TITLE
no file named ./emulator

### ISSUE THREAD

**Issue by synaption** [rogerdahl/WS2812B-NeoPixel-Emulator#3]
I ran make and cmake, but I do not see a file named ./emulator nor does running the command work.  make did get to 100%.

**Comment by rogerdahl** [comment]
Can you tell me a bit about your software development environment?

**Comment by synaption** [comment]
I've got identical results on a desktop running ubuntu 18.04 and a vm running ubuntu 20.04.  Both are nearly fresh installs.

**Comment by synaption** [comment]
I found the file in bin.   I assume I am supposed to know that, but apparently I didn't.

**Comment by rogerdahl** [comment]
Sorry, error in the instructions. Fixing it now.
